version: '3.7'
networks:
  auth-net:
    driver: bridge
services:
  test:
    image: ghcr.io/karun-singh/aaa-test:latest
    environment:
      - AUTH_URL=https://authorization.iudx.org.in
      - LOG_LEVEL=INFO
      - AUTH_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/aaa-config-test.json:/usr/share/app/configs/config-test.json
      - /home/ubuntu/configs/aaa-keystore.jks:/usr/share/app/configs/keystore.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ./src/:/usr/share/app/src
      - ${WORKSPACE}:/tmp/test
    command: bash -c "docker/runTests.sh"
    networks: 
      - auth-net

  integTest:
    image: ghcr.io/karun-singh/aaa-test:latest
    environment:
      - AUTH_URL=https://authorization.iudx.org.in
      - LOG_LEVEL=INFO
      - AUTH_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/aaa-config-integ.json:/usr/share/app/configs/config-dev.json
      - /home/ubuntu/configs/aaa-keystore.jks:/usr/share/app/configs/keystore.jks
      - /home/ubuntu/configs/aaa-flyway.conf:/usr/share/app/flyway.conf
      - ./docs/:/usr/share/app/docs
      - ./src/:/usr/share/app/src
    command: bash -c "mvn clean compile exec:java@aaa-server"
    ports:
      - "8443:8443"
    networks:
      - auth-net
