version: '3.7'
networks:
  auth-net:
    driver: bridge
services:
  test:
    image: ghcr.io/datakaveri/aaa-test:latest
    environment:
      - AUTH_URL=https://authorization.iudx.org.in
      - LOG_LEVEL=INFO
      - AUTH_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/4.5.0/aaa-config-test.json:/usr/share/app/configs/config-test.json
      - /home/ubuntu/configs/4.5.0/aaa-keystore.jks:/usr/share/app/configs/keystore.jks
      - ./spotbugs-exclude.xml:/usr/share/app/spotbugs-exclude.xml
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ./src/:/usr/share/app/src
      - ${WORKSPACE}:/tmp/test
    command: bash -c "docker/runTests.sh"
    networks: 
      - auth-net

  integTest:
    image: ghcr.io/datakaveri/aaa-depl:latest
    environment:
      - AUTH_URL=https://authorization.iudx.org.in
      - LOG_LEVEL=INFO
      - AUTH_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/4.5.0/aaa-config-integ.json:/usr/share/app/configs/config.json
      - /home/ubuntu/configs/4.5.0/aaa-keystore.jks:/usr/share/app/configs/keystore.jks
    depends_on:
      - "zookeeper"
    command: bash -c "exec java $$AUTH_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - auth-net

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - auth-net
